#~ Goal Selection Param File ~#

#~ General Parameters
slam_map: /map                              # SLAM map topic
coverage_map: /coverage_map                 # Coverage map topic
map_frame: map                              # Map frame
base_footprint_frame: base_footprint        # Base footprint frame
resolution: 0.05                            # Map resolution

#~ Coverage Parameters
num_of_sensors: 1                           # Number of coverage sensors on the robot
#~ Sensor 1 - Asus Xtion Pro camera
dist_of_use_1: 3.5                          # Sensor's distance of use (in meters)
hfov_1: 58                                  # Sensor's Horizontal Field of View (in degrees)
sensor_frame_1: base_link              # Sensor frame
#~ Sensor 2 - Random
#dist_of_use_2: 1.5                          # Sensor's distance of use (in meters)
#hfov_2: 30                                  # Sensor's Horizontal Field of View (in degrees)
#$sensor_frame_2: camera_depth_optical_frame  # Sensor frame
