#Goal Selection Param File ~#

#~ General Parameters
slam_map: /map                              # SLAM map topic
coverage_map: /coverage_map                 # Coverage map topic
map_frame: map                              # Map frame
base_footprint_frame: base_footprint        # Base footprint frame
sensor_frame: base_link
dist_of_use: 4
field_of_view: 60
# velocity pub topic
velocity_pub: '/mobile_base/commands/velocity'
# resolution used to be 0.05
# change also delta param according in
# gmapping.launch.xml in turtlebot
# navigation package
resolution: 0.04                # Map resolution

# Radius around pose
radius: 2

  # Willow params
width: 864
height: 896

origin_x: -16.36
origin_y: -18.92


## corridor params
#width: 608
#height: 672
#
#origin_x: -12.52
#origin_y: -13.80

### Big Map params 
#width: 1088
#height: 1344
#
#origin_x: -26.6
#origin_y: -26.6

